Dropped support for Inkscape <1.2, Added support for 1.2's "actions"

diff --git a/svg-stroke-to-path b/svg-stroke-to-path
--- a/svg-stroke-to-path
+++ b/svg-stroke-to-path
@@ -2,25 +2,17 @@
 
 display_help() {
     echo
-    echo "Usage: svg-stroke-to-path select_method select_attr file ..."
-    echo
-    echo "  select_method can be one of:"
-    echo "    * All - Select all objects"
-    echo "    * AllInAllLayers - Select all objects in all visible and"
-    echo "      unlocked layers"
-    echo "    * SameFillStroke - Select all objects with the same fill"
-    echo "      and stroke as the selected objects"
-    echo "    * SameFillColor - Select all objects with the same fill"
-    echo "      as the selected objects"
-    echo "    * SameStrokeColor - Select all objects with the same"
-    echo "      stroke as the selected objects"
-    echo "    * SameStrokeStyle - Select all objects with the same stroke"
-    echo "      style (width, dash, markers) as the selected objects"
-    echo
-    echo "  select_attr can be a variety of SVG attributes, for example:"
-    echo "    * 'stroke=\"#000\"'"
-    echo "    * 'fill=\"#000\"'"
-    echo "    * 'stroke=\"red\" stroke-weight=\"2\"'"
+    echo "Usage: svg-stroke-to-path select_attr file ..."
+    echo 
+    echo "  select_attr can be"
+    echo "    * 'all' to select all elements"
+    echo 
+    echo "  or, it can be a variety of CSS selectors, for example:"
+    echo "    * 'path' to select only <path> objects"
+    echo "    * 'rect,circle' to select both <rect> and <circle> elements"
+    echo "    * '[stroke=\"#000000\"]' to select elements with specific attributes"
+    echo "    * 'path[stroke=\"#000000\"]' to select only paths with specific attributes"
+    echo "    * '[stroke=\"#000000\"][stroke-weight=\"0.5\"]' to select multiple attributes"
     echo
 }
 
@@ -56,35 +48,31 @@ read_inkscape_version() {
 
 read_inkscape_version
 
-# Used later to distinguish between 0.92 and 1.0
+# Used later to distinguish between 1.1 and 1.2+
 semver_greater_than() {
     test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
 }
 
-# Read the arguments
-select_method=$1
-select_attr=$2
-shift 2
+# Require that Inkscape 1.2 or higher is installed
+if ! semver_greater_than ${inkscape_bin_version} 1.1.999; then
+    echo "Error: Inkscape Version ${inkscape_bin_version} not supported."
+    echo "Please upgrade to Inkscape 1.2 or higher, or use an older version of svg-stroke-to-path at the commit 56ee0fc."
+fi
 
-# Validate that select method is a valid string
-case ${select_method} in
-    All|\
-    AllInAllLayers|\
-    SameFillStroke|\
-    SameFillColor|\
-    SameStrokeColor|\
-    SameStrokeStyle);;
-    *)
-    display_help;
-    echo "Error: select_method '$select_method' is not valid"
-    exit 1;;
-esac
+# Read the arguments
+select_attr=$1
+shift 1
 
 # Validate that the select attr is set
 if [[ -z "$select_attr" ]]; then
     display_help
     echo "Error: select_attr required"
     exit 1
+fi
+
+select_method='select-by-selector'
+if [[ "$select_attr" == "all" ]]; then
+  select_method='select-all'
 fi
 
 validate_file() {
@@ -109,57 +97,21 @@ do
 done
 
 convert_file() {
-    select_method=$1
-    select_attr=$2
-    input_filename=$3
-
-    # Read input file
-    input_content=`cat "$input_filename"`
-
-    # Get position of closing `svg` tag in the SVG
-    svg_close_index=`echo "$input_content" | grep -b -o "</svg>" | cut -d: -f1`
-
-    # Generate the "selector" element
-    selector_object_id='_StrokeToPathSelectorObject'
-    selector_object="    <path\
-     id=\"${selector_object_id}\"\
-     ${select_attr}\
-     d=\"M0 0 H 0\"/>\n"
-
-    # Insert "selector" element into the SVG
-    modified_input="${input_content:0:$svg_close_index}\
-    $selector_object\
-    ${input_content:$svg_close_index}"
-
-    # Store the new SVG
-    echo "$modified_input" > "$input_filename"
+    select_attr=$1
+    input_filename=$2
 
     # Convert stroke to path by selecting the "selector" element and use
     # Inkscape's selector query to select similar objects and convert
     # stroke to path
     # For more information on Inkscape's command line, see:
     # http://wiki.inkscape.org/wiki/index.php/Using_the_Command_Line
-    if semver_greater_than ${inkscape_bin_version} 1; then
-        # Post 0.92.x (Essentially 1.0)
-        ${inkscape_bin} --batch-process \
-            --select=${selector_object_id}\
-            --verb "EditSelect$select_method;StrokeToPath;FileSave"\
-            "$input_filename"
-    else
-        # 0.92.x
-        ${inkscape_bin} -f "$input_filename"\
-            --select=${selector_object_id}\
-            --verb="EditSelect$select_method"\
-            --verb="StrokeToPath"\
-            --verb="EditDeselect"\
-            --select=${selector_object_id}\
-            --verb="EditDelete"\
-            --verb="FileSave"\
-            --verb="FileQuit"
-    fi
+    ${inkscape_bin} \
+        --actions="$select_method:$select_attr;object-stroke-to-path" \
+        --export-filename="$input_filename" \
+        "$input_filename"
 }
 
 for file in "$@"
 do
-    convert_file ${select_method} "$select_attr" `pwd`"/$file"
+    convert_file "$select_attr" `pwd`"/$file"
 done
